### ISSUE TITLE
Tunnels information returned by REST API can't be parsed

### ISSUE THREAD

**Issue by NatalliaSamarava** [saucelabs/saucerest-java#527]
**Steps to reproduce:**
Use `SauceConnectEndpoint.getTunnelsInformationForAUser` to get tunnels information

**Actual**:
```
Caused by: com.squareup.moshi.JsonDataException: Expected an int but was 18446744073709551615 at path $[0].metadata.nofile_limit
	at com.squareup.moshi.JsonUtf8Reader.nextInt(JsonUtf8Reader.java:965) ~[moshi-1.15.1.jar:?]
	at com.squareup.moshi.StandardJsonAdapters$7.fromJson(StandardJsonAdapters.java:196) ~[moshi-1.15.1.jar:?]
	at com.squareup.moshi.StandardJsonAdapters$7.fromJson(StandardJsonAdapters.java:193) ~[moshi-1.15.1.jar:?]
	at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:41) ~[moshi-1.15.1.jar:?]
	at com.squareup.moshi.ClassJsonAdapter$FieldBinding.read(ClassJsonAdapter.java:245) ~[moshi-1.15.1.jar:?]
	at com.squareup.moshi.ClassJsonAdapter.fromJson(ClassJsonAdapter.java:205) ~[moshi-1.15.1.jar:?]
	at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:41) ~[moshi-1.15.1.jar:?]
	at com.squareup.moshi.ClassJsonAdapter$FieldBinding.read(ClassJsonAdapter.java:245) ~[moshi-1.15.1.jar:?]
	at com.squareup.moshi.ClassJsonAdapter.fromJson(ClassJsonAdapter.java:205) ~[moshi-1.15.1.jar:?]
	at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:41) ~[moshi-1.15.1.jar:?]
	at com.squareup.moshi.CollectionJsonAdapter.fromJson(CollectionJsonAdapter.java:81) ~[moshi-1.15.1.jar:?]
	at com.squareup.moshi.CollectionJsonAdapter$2.fromJson(CollectionJsonAdapter.java:55) ~[moshi-1.15.1.jar:?]
	at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:41) ~[moshi-1.15.1.jar:?]
	at com.squareup.moshi.JsonAdapter.fromJson(JsonAdapter.java:70) ~[moshi-1.15.1.jar:?]
	at com.saucelabs.saucerest.api.AbstractEndpoint.deserializeJSONArray(AbstractEndpoint.java:405) ~[saucerest-2.5.0.jar:2.5.0]
	at com.saucelabs.saucerest.api.AbstractEndpoint.deserializeJSONArray(AbstractEndpoint.java:418) ~[saucerest-2.5.0.jar:2.5.0]
	at com.saucelabs.saucerest.api.SauceConnectEndpoint.getTunnelsInformationForAUser(SauceConnectEndpoint.java:66) ~[saucerest-2.5.0.jar:2.5.0]
	at com.saucelabs.saucerest.api.SauceConnectEndpoint.getTunnelsInformationForAUser(SauceConnectEndpoint.java:42) ~[saucerest-2.5.0.jar:2.5.0]
	at com.saucelabs.ci.sauceconnect.AbstractSauceTunnelManager.activeTunnelID(AbstractSauceTunnelManager.java:599) ~[ci-sauce-1.180.jar:1.180]
	at com.saucelabs.ci.sauceconnect.AbstractSauceTunnelManager.openConnection(AbstractSauceTunnelManager.java:420) ~[ci-sauce-1.180.jar:1.180]
```

**Expected**: tunnels information is successfully parsed

**Comment by diemol** [comment]
PR was merged and released. Thank you, @valfirst!
